---
- name: Update and then safe upgrade installed packages (apt)
  apt:
    update_cache=yes
    upgrade=yes
  become: yes
  become_method: sudo

- name: Install Packages to allow apt to use repos over HTTPS 
  package: 
    name: "{{ item }}"
    state: present
  become: yes
  become_method: sudo
  with_items:
    - curl
    - apt-transport-https
    - ca-certificates
    - software-properties-common
