---
- name: Update Debian based systems
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Update Redhat based ystems
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Install Common Packages
  package: 
    name: "{{ item }}"
    state: present
  become: yes
  become_method: sudo
  with_items:
    - vim
